n = input('Digite algo: ')
print(f'tipo primitivo {type(n)}')
print(f'Só tem espaços? {n.isspace()}')
print(f'É um numero? {n.isnumeric()}')
print(f'É alfabético? {n.isalpha()}')
print(f'É alfanumérico? {n.isalnum()}')
print(f'Esta em maiúscula? {n.isupper()}')
print(f'Esta em minúscula? {n.islower()}')
print(f'Está captalizada? {n.istitle()}')